Add batch inference tutorial
valohai/docs pull request #132
Opened 2021-05-18 12:46 UTC by orasimus

2021-05-18 14:05 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +
```suggestion
* ``pip install --upgrade valohai-cli``

```

2021-05-18 14:06 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +
I'd remove this and just include it in the requirements, like in some of the other tutorials

```suggestion

```

2021-05-18 14:11 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +   :alt: Results of our batch inference execution
```suggestion
   :alt: Results of our batch inference execution
   
.. seealso::

    * `Valohai CLI </tutorials/valohai-cli/>`_
    * `Using Docker Images </topic-guides/docker-images/>>`_
    * `Valohai APIs </tutorials/apis/>`_
```

2021-05-18 14:14 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +            default: s3://valohai-public-files/tensorflow-batch-inference-tutorial/model.h5
```suggestion
          default: s3://valohai-public-files/tensorflow-batch-inference-tutorial/model.h5
```

2021-05-18 14:14 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +            default: s3://valohai-public-files/tensorflow-batch-inference-tutorial/images.zip
```suggestion
          default: s3://valohai-public-files/tensorflow-batch-inference-tutorial/images.zip
```

2021-05-18 14:17 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +
```suggestion
Let’s run another execution on Valohai:

.. code-block:: bash
    vh exec run --adhoc "Batch Inference"
    
```

2021-05-18 14:27 UTC, DrazenDodik commented on source/tutorials/batch-inference/index.rst
> +    If you want to, you can train the required model by following the tutorial `here <https://www.tensorflow.org/tutorials/quickstart/beginner>`_.
If you want to, you can train the required model by following our `Valohai 101 tutorial </tutorials/quickstart/>`_.

2021-05-18 14:30 UTC, DrazenDodik requested changes
Looks good!  Added a couple of small comments.

I'd prefer if we tie this into the official Valohai quickstart, rather than the Tensorflow sample without any Valohai parts.

Did you try to predict with the model? What kind of results did you get? If the accuracy is as off as I'm seeing, then we should add a disclaimer that the model was trained with just a few epochs (like the TF sample goes through only 5 epochs)

2021-05-19 07:39 UTC, orasimus commented
I just checked and it got 5/10 correct. One image is of an X, so any answer is wrong.

So I'd say the model is okay, the issue is more with my hand-drawn input images, which probably don't look much like the rest of the MNIST dataset.

2021-05-19 07:50 UTC, merged