Add sections about pipeline conditions and parameter edges
valohai/docs pull request #156
Opened 2021-08-03 15:08 UTC by noorula

These are now under Valohai 101 -> Create pipeline. Might make sense to reorganize to make the docs more clear.

2021-08-03 15:10 UTC, noorula commented
Seems I also put the metadata update in the same pull request... The purpose of that is to make it more clear that metadata can be used in other purposes than just visuals as well.

2021-08-04 08:35 UTC, orasimus commented
Left some comments, mainly on simplifying the text further. In general looks good.

2021-08-09 07:35 UTC, orasimus requested changes

2021-08-09 13:08 UTC, orasimus approved these changes
LGTM

2021-08-09 13:08 UTC, merged