Fix wording
valohai/docs pull request #180
Opened 2021-12-17 11:34 UTC by DennisBunea

2021-12-17 11:47 UTC, noorula requested changes
Looking good, one small change.

2021-12-17 11:47 UTC, noorula commented on source/howto/code-repository/private-github-repository/index.rst
> +###################################
```suggestion
###################################
```

2021-12-21 07:59 UTC, DrazenDodik commented
- `github-key-2.png` shows adding a deploy key to GitHub. That looks like a private key to me, instead of a public key? The private key goes to Valohai (starts with ---BEGIN) and the public key goes to GitHub
- `github-key-3.png` is an old screenshot from a different repo. Here it shows ruksi/my-project. I'd update this screenshot.
- Looks like the screenshots on the Valohai UI haven't been updated. Can you check those? Example below: 
![image](https://user-images.githubusercontent.com/26482561/146892428-6e4a405b-ce1c-4183-85e8-03bc685b2847.png)
If you look at the code, it looks like these files are in a different location. I'd maybe move them to /howto/code-repository/, replace the images with new screenshots, and then update the code to point to new images.
```
.. image:: /tutorials/valohai-key-1.png
   :alt: Valohai - route to repository settings
``` 

I'd resize the images, because some of them are massive now and will cause slower loading times. For example `source/howto/code-repository/private-github-repository/github-key-2.png` used to be W: 999px | H: 656px and is now W: 3663px | H: 1541px

Do the same changes across GitHub/BitBucket/GitLab

2022-01-13 12:15 UTC, noorula approved these changes
Fix the email and the private key, then good to go.

2022-01-19 09:14 UTC, noorula approved these changes
Looks good!

2022-01-19 11:11 UTC, merged